apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniturbo
  labels:
    app: miniturbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniturbo
  template:
    metadata:
      labels:
        app: miniturbo
    spec:
      containers:
      - name: miniturbo
        image: silentbit001/miniturbo
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: miniturbo
spec:
  type: NodePort
  selector:
    app: miniturbo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080