apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: spotify/cassandra
        ports:
        - containerPort: 9042
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: cassandra
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042