apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cassandra-admin
  labels:
    app: cassandra-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-admin
  template:
    metadata:
      labels:
        app: cassandra-admin
    spec:
      containers:
      - name: cassandra-admin
        image: delermando/docker-cassandra-web:v0.4.0
        ports:
        - containerPort: 3000
        command: 
        - "/bin/sh"
        args: 
        - "-c" 
        - "cassandra-web --hosts $CASSANDRA_SERVICE_HOST --port 9042 --username cassandra --password cassandra"
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: cassandra-admin
spec:
  type: NodePort
  selector:
    app: cassandra-admin
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000