apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:4.0.11-alpine
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379