apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.8-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: server
    port: 5672
    targetPort: 5672
  - name: manager
    port: 15672
    targetPort: 15672