apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis-admin
  labels:
    app: redis-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-admin
  template:
    metadata:
      labels:
        app: redis-admin
    spec:
      containers:
      - name: redis-admin
        image: marian/rebrow
        ports:
        - containerPort: 5001
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: redis-admin
spec:
  type: NodePort
  selector:
    app: redis-admin
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001