apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: turq
  labels:
    app: turq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turq
  template:
    metadata:
      labels:
        app: turq
    spec:
      containers:
      - name: turq
        image: python:3.6.6-alpine
        command: 
        - "/bin/sh"
        args: 
        - "-c" 
        - "pip install turq requests redis cassandra-driver pymongo pika python-consul hvac && turq -P ''"
        ports:
        - containerPort: 13085
        - containerPort: 13086

---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: turq
spec:
  type: NodePort
  selector:
    app: turq
  ports:
  - name: editor
    port: 13086
    targetPort: 13086
  - name: server
    port: 13085
    targetPort: 13085